"""
Phase 2: Train the SD3.5 conditioning inverter f_θ.

Loads the (image, conditioning) dataset generated by
generate_inversion_training_data.py and trains SD35ConditioningInverter
so that f_θ(image) ≈ (pooled_embeds, seq_embeds[:154]) for images
generated by SD3.5.

Usage
-----
conda run -n superdiff python scripts/train_inverter.py \
    [--data-dir experiments/inversion/training_data] \
    [--ckpt-dir ckpt/inverter] \
    [--epochs 50] \
    [--batch-size 16] \
    [--lr 1e-4] \
    [--lambda-seq 0.1] \
    [--val-fraction 0.1] \
    [--clip-model-id openai/clip-vit-large-patch14]
"""

import argparse
import json
import os
import sys
import random
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from models.sd35_inverter import (
    SD35ConditioningInverter,
    inversion_loss,
    save_inverter,
    CLIP_TOKENS,
)


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class InversionDataset(Dataset):
    """
    Each item: (image_tensor, pooled_embeds, seq_embeds_clip)

    image_tensor     : (3, 224, 224) — CLIP-preprocessed
    pooled_embeds    : (2048,)       — float32
    seq_embeds_clip  : (154, 4096)   — float32, first 154 tokens of seq_embeds
    """

    # CLIP normalisation
    CLIP_MEAN = [0.48145466, 0.4578275, 0.40821073]
    CLIP_STD  = [0.26862954, 0.26130258, 0.27577711]

    def __init__(self, records: list):
        self.records = records   # list of (image_path, cond_path)
        self.transform = transforms.Compose([
            transforms.Resize(224, interpolation=transforms.InterpolationMode.BICUBIC),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(self.CLIP_MEAN, self.CLIP_STD),
        ])

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        img_path, cond_path = self.records[idx]

        image = Image.open(img_path).convert("RGB")
        image = self.transform(image)   # (3, 224, 224)

        cond = torch.load(cond_path, map_location="cpu", weights_only=True)
        pooled = cond["pooled_embeds"].squeeze(0).float()  # (2048,)
        seq    = cond["seq_embeds"].squeeze(0).float()     # (410, 4096)

        return image, pooled, seq


# ---------------------------------------------------------------------------
# Build records from dataset_index.json
# ---------------------------------------------------------------------------

def build_records(data_dir: Path) -> list:
    index_path = data_dir / "dataset_index.json"
    with open(index_path) as f:
        index = json.load(f)

    records = []
    for entry in index:
        prompt_dir = Path(entry["path"])
        cond_path  = prompt_dir / "conditioning.pt"
        if not cond_path.exists():
            continue
        for img_path in sorted(prompt_dir.glob("img_*.png")):
            records.append((str(img_path), str(cond_path)))

    return records


def split_records(records: list, val_fraction: float, seed: int = 42):
    """Split by prompt directory (not by image) to avoid data leakage."""
    # Group by cond_path (one per prompt)
    from collections import defaultdict
    by_prompt = defaultdict(list)
    for img_path, cond_path in records:
        by_prompt[cond_path].append((img_path, cond_path))

    prompts = list(by_prompt.keys())
    rng = random.Random(seed)
    rng.shuffle(prompts)

    n_val = max(1, int(len(prompts) * val_fraction))
    val_prompts  = set(prompts[:n_val])
    train_prompts = set(prompts[n_val:])

    train_records = [r for p in train_prompts for r in by_prompt[p]]
    val_records   = [r for p in val_prompts   for r in by_prompt[p]]
    return train_records, val_records


# ---------------------------------------------------------------------------
# Training loop
# ---------------------------------------------------------------------------

def train_one_epoch(model, loader, optimizer, lambda_seq, device):
    model.train()
    total_loss = pooled_mse = seq_mse = pooled_cos = 0.0

    for images, true_pooled, true_seq in loader:
        images      = images.to(device)
        true_pooled = true_pooled.to(device)
        true_seq    = true_seq.to(device)

        pred_pooled, pred_seq_clip = model.predict_clip_seq_only(images)

        losses = inversion_loss(
            pred_pooled, pred_seq_clip,
            true_pooled, true_seq,
            lambda_seq=lambda_seq,
        )

        optimizer.zero_grad()
        losses["total"].backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        n = images.shape[0]
        total_loss  += losses["total"].item()     * n
        pooled_mse  += losses["pooled_mse"].item() * n
        seq_mse     += losses["seq_mse"].item()    * n
        pooled_cos  += losses["pooled_cos"].item() * n

    N = len(loader.dataset)
    return {
        "loss":       total_loss / N,
        "pooled_mse": pooled_mse / N,
        "seq_mse":    seq_mse    / N,
        "pooled_cos": pooled_cos / N,
    }


@torch.no_grad()
def validate(model, loader, lambda_seq, device):
    model.eval()
    total_loss = pooled_mse = seq_mse = pooled_cos = 0.0

    for images, true_pooled, true_seq in loader:
        images      = images.to(device)
        true_pooled = true_pooled.to(device)
        true_seq    = true_seq.to(device)

        pred_pooled, pred_seq_clip = model.predict_clip_seq_only(images)
        losses = inversion_loss(
            pred_pooled, pred_seq_clip,
            true_pooled, true_seq,
            lambda_seq=lambda_seq,
        )

        n = images.shape[0]
        total_loss  += losses["total"].item()     * n
        pooled_mse  += losses["pooled_mse"].item() * n
        seq_mse     += losses["seq_mse"].item()    * n
        pooled_cos  += losses["pooled_cos"].item() * n

    N = len(loader.dataset)
    return {
        "loss":       total_loss / N,
        "pooled_mse": pooled_mse / N,
        "seq_mse":    seq_mse    / N,
        "pooled_cos": pooled_cos / N,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Train SD3.5 conditioning inverter")
    p.add_argument("--data-dir",       default="experiments/inversion/training_data")
    p.add_argument("--ckpt-dir",       default="ckpt/inverter")
    p.add_argument("--epochs",         type=int,   default=50)
    p.add_argument("--batch-size",     type=int,   default=16)
    p.add_argument("--lr",             type=float, default=1e-4)
    p.add_argument("--weight-decay",   type=float, default=1e-2)
    p.add_argument("--lambda-seq",     type=float, default=0.1,
                   help="Weight for sequence MSE loss term")
    p.add_argument("--val-fraction",   type=float, default=0.1)
    p.add_argument("--warmup-epochs",  type=int,   default=5)
    p.add_argument("--clip-model-id",  default="openai/clip-vit-large-patch14")
    p.add_argument("--num-workers",    type=int,   default=4)
    p.add_argument("--seed",           type=int,   default=42)
    return p.parse_args()


def main():
    args = parse_args()
    torch.manual_seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    data_dir = Path(args.data_dir)
    ckpt_dir = Path(args.ckpt_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    # ---- Dataset ----
    print("Building dataset ...")
    records = build_records(data_dir)
    train_records, val_records = split_records(records, args.val_fraction, args.seed)
    print(f"  Train: {len(train_records)} images  |  Val: {len(val_records)} images")

    train_ds = InversionDataset(train_records)
    val_ds   = InversionDataset(val_records)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=args.num_workers, pin_memory=True,
                              drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False,
                              num_workers=args.num_workers, pin_memory=True)

    # ---- Model ----
    print(f"Loading inverter (CLIP: {args.clip_model_id}) ...")
    model = SD35ConditioningInverter(
        clip_model_id=args.clip_model_id,
        freeze_clip=True,
    ).to(device)
    print(f"  Trainable params: {model.num_trainable_params / 1e6:.1f}M  "
          f"| Total params: {model.num_total_params / 1e6:.1f}M")

    # ---- Optimiser + LR schedule ----
    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=args.lr, weight_decay=args.weight_decay,
    )

    # Linear warmup then cosine decay
    def lr_lambda(epoch):
        if epoch < args.warmup_epochs:
            return float(epoch + 1) / float(args.warmup_epochs)
        progress = (epoch - args.warmup_epochs) / max(1, args.epochs - args.warmup_epochs)
        import math
        return 0.5 * (1.0 + math.cos(math.pi * progress))

    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

    # ---- Training ----
    best_val_loss = float("inf")
    log = []

    for epoch in range(1, args.epochs + 1):
        train_metrics = train_one_epoch(model, train_loader, optimizer,
                                         args.lambda_seq, device)
        val_metrics   = validate(model, val_loader, args.lambda_seq, device)
        scheduler.step()

        lr_now = optimizer.param_groups[0]["lr"]
        print(
            f"Epoch {epoch:3d}/{args.epochs}  "
            f"train_loss={train_metrics['loss']:.4f}  "
            f"val_loss={val_metrics['loss']:.4f}  "
            f"val_cos={val_metrics['pooled_cos']:.4f}  "
            f"lr={lr_now:.2e}"
        )

        log.append({"epoch": epoch, "train": train_metrics, "val": val_metrics,
                     "lr": lr_now})

        # Save best checkpoint
        if val_metrics["loss"] < best_val_loss:
            best_val_loss = val_metrics["loss"]
            save_inverter(model, str(ckpt_dir / "best.pt"))
            print(f"  → best checkpoint saved (val_loss={best_val_loss:.4f})")

        # Save latest checkpoint every 10 epochs
        if epoch % 10 == 0:
            save_inverter(model, str(ckpt_dir / f"epoch_{epoch:04d}.pt"))

    # Save final
    save_inverter(model, str(ckpt_dir / "final.pt"))

    # Save training log
    import json as _json
    with open(ckpt_dir / "training_log.json", "w") as f:
        _json.dump(log, f, indent=2)

    print(f"\nTraining complete. Best val_loss: {best_val_loss:.4f}")
    print(f"Checkpoints saved to: {ckpt_dir}")


if __name__ == "__main__":
    main()
