"""
SD35ConditioningInverter
========================
A lightweight image-to-conditioning inverter calibrated to SD3.5.

Given an image generated by SD3.5 (or SuperDiff-AND), predicts the
SD3.5 conditioning vectors (pooled_embeds, seq_embeds) that would
reproduce it when passed back into the SD3.5 transformer.

Architecture
------------
- Backbone: CLIP ViT-L/14 (frozen), 768-dim patch features
- Pooled head: MLP 768 → 1024 → 2048 (pooled_prompt_embeds)
- Sequence head: cross-attention decoder
    learned queries (154, 768) attend over CLIP patch tokens → Linear(768, 4096)
    outputs seq_embeds for the CLIP portion (154 tokens)
    T5 portion (positions 154:) is zeroed at inference (scope limitation)

Training targets come from get_sd3_text_embedding() in notebooks/utils.py:
    prompt_embeds:        (B, 410, 4096)  — we supervise on [:154] only
    pooled_prompt_embeds: (B, 2048)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import CLIPVisionModelWithProjection, CLIPImageProcessor


# ---------------------------------------------------------------------------
# CLIP preprocessing constants
# ---------------------------------------------------------------------------
CLIP_MEAN = [0.48145466, 0.4578275, 0.40821073]
CLIP_STD  = [0.26862954, 0.26130258, 0.27577711]
CLIP_SIZE = 224

# SD3.5 conditioning dimensions
POOLED_DIM  = 2048   # CLIP-L (768) + CLIP-G (1280)
SEQ_DIM     = 4096   # T5-XXL hidden size (all seq positions use this dim)
CLIP_TOKENS = 154    # CLIP-L (77) + CLIP-G (77) tokens
T5_TOKENS   = 256    # T5 portion (zeroed at inference)
TOTAL_TOKENS = CLIP_TOKENS + T5_TOKENS   # 410


def make_clip_preprocessor(device: torch.device):
    """Return a callable that preprocesses PIL images or [0,1] tensors to CLIP input."""
    mean = torch.tensor(CLIP_MEAN, device=device).view(1, 3, 1, 1)
    std  = torch.tensor(CLIP_STD,  device=device).view(1, 3, 1, 1)

    def preprocess(images: torch.Tensor) -> torch.Tensor:
        """
        images: (B, 3, H, W) float32 in [0, 1]
        returns: (B, 3, 224, 224) normalised for CLIP ViT
        """
        x = F.interpolate(images.float(), size=(CLIP_SIZE, CLIP_SIZE), mode="bicubic",
                          align_corners=False)
        x = x.clamp(0.0, 1.0)
        x = (x - mean) / std
        return x

    return preprocess


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------

class SD35ConditioningInverter(nn.Module):
    """
    Predicts SD3.5 conditioning (pooled_embeds, seq_embeds) from an image.

    Parameters
    ----------
    clip_model_id : str
        HuggingFace model id for the CLIP vision backbone.
    freeze_clip : bool
        If True (default), CLIP backbone weights are frozen.
    """

    def __init__(
        self,
        clip_model_id: str = "openai/clip-vit-large-patch14",
        freeze_clip: bool = True,
    ):
        super().__init__()

        # ---- Visual backbone ----
        self.clip_vision = CLIPVisionModelWithProjection.from_pretrained(clip_model_id)
        if freeze_clip:
            for p in self.clip_vision.parameters():
                p.requires_grad_(False)

        clip_hidden = self.clip_vision.config.hidden_size  # 768 for ViT-L/14

        # ---- Pooled head: 768 → 1024 → 2048 ----
        self.pooled_head = nn.Sequential(
            nn.Linear(clip_hidden, 1024),
            nn.GELU(),
            nn.LayerNorm(1024),
            nn.Linear(1024, POOLED_DIM),
        )

        # ---- Sequence head: cross-attention decoder ----
        # 154 learned query tokens attend over CLIP patch features,
        # then project to 4096.
        self.query_tokens = nn.Parameter(torch.randn(CLIP_TOKENS, clip_hidden) * 0.02)
        self.cross_attn   = nn.MultiheadAttention(
            embed_dim=clip_hidden,
            num_heads=8,
            batch_first=True,
            dropout=0.0,
        )
        self.seq_norm = nn.LayerNorm(clip_hidden)
        self.seq_proj = nn.Linear(clip_hidden, SEQ_DIM)

    # ------------------------------------------------------------------
    def forward(self, images: torch.Tensor):
        """
        Parameters
        ----------
        images : (B, 3, 224, 224) float32, CLIP-normalised

        Returns
        -------
        pooled_embeds : (B, 2048)
        seq_embeds    : (B, 410, 4096)  — positions [154:] are zero
        """
        B = images.shape[0]

        # CLIP patch features: (B, 257, 768) — first token is [CLS]
        vision_out = self.clip_vision(pixel_values=images, return_dict=True)
        patch_feats = vision_out.last_hidden_state  # (B, 257, 768)
        cls_feat    = patch_feats[:, 0]             # (B, 768)

        # Pooled head
        pooled = self.pooled_head(cls_feat)         # (B, 2048)

        # Sequence head via cross-attention
        queries = self.query_tokens.unsqueeze(0).expand(B, -1, -1)  # (B, 154, 768)
        attn_out, _ = self.cross_attn(queries, patch_feats, patch_feats)  # (B, 154, 768)
        attn_out = self.seq_norm(attn_out)
        seq_clip = self.seq_proj(attn_out)           # (B, 154, 4096)

        # Zero-pad T5 portion to match SD3.5 expected shape (B, 410, 4096)
        t5_zeros = torch.zeros(B, T5_TOKENS, SEQ_DIM, device=seq_clip.device,
                               dtype=seq_clip.dtype)
        seq_embeds = torch.cat([seq_clip, t5_zeros], dim=1)  # (B, 410, 4096)

        return pooled, seq_embeds

    # ------------------------------------------------------------------
    def predict_clip_seq_only(self, images: torch.Tensor):
        """
        Returns only the CLIP-portion sequence embeddings (B, 154, 4096),
        without zero-padding. Useful for computing training loss against
        the first 154 tokens of the true prompt_embeds.
        """
        B = images.shape[0]
        vision_out = self.clip_vision(pixel_values=images, return_dict=True)
        patch_feats = vision_out.last_hidden_state
        cls_feat    = patch_feats[:, 0]

        pooled = self.pooled_head(cls_feat)

        queries  = self.query_tokens.unsqueeze(0).expand(B, -1, -1)
        attn_out, _ = self.cross_attn(queries, patch_feats, patch_feats)
        attn_out = self.seq_norm(attn_out)
        seq_clip = self.seq_proj(attn_out)

        return pooled, seq_clip   # (B, 2048), (B, 154, 4096)

    # ------------------------------------------------------------------
    @property
    def num_trainable_params(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    @property
    def num_total_params(self) -> int:
        return sum(p.numel() for p in self.parameters())


# ---------------------------------------------------------------------------
# Loss
# ---------------------------------------------------------------------------

def inversion_loss(
    pred_pooled: torch.Tensor,
    pred_seq_clip: torch.Tensor,
    true_pooled: torch.Tensor,
    true_seq: torch.Tensor,
    lambda_seq: float = 0.1,
) -> dict:
    """
    Compute inverter training loss.

    Parameters
    ----------
    pred_pooled   : (B, 2048)
    pred_seq_clip : (B, 154, 4096)
    true_pooled   : (B, 2048)
    true_seq      : (B, 410, 4096)  — we use only [:154]
    lambda_seq    : weight for sequence MSE term

    Returns
    -------
    dict with keys: total, pooled_mse, seq_mse, pooled_cos
    """
    loss_pooled = F.mse_loss(pred_pooled, true_pooled)
    loss_seq    = F.mse_loss(pred_seq_clip, true_seq[:, :CLIP_TOKENS].float())

    # Cosine similarity in pooled space (monitoring metric, not used in grad)
    with torch.no_grad():
        cos = F.cosine_similarity(pred_pooled, true_pooled, dim=-1).mean()

    total = loss_pooled + lambda_seq * loss_seq
    return {
        "total":       total,
        "pooled_mse":  loss_pooled,
        "seq_mse":     loss_seq,
        "pooled_cos":  cos,
    }


# ---------------------------------------------------------------------------
# Checkpoint helpers
# ---------------------------------------------------------------------------

def save_inverter(model: SD35ConditioningInverter, path: str):
    torch.save({"state_dict": model.state_dict()}, path)


def load_inverter(
    path: str,
    clip_model_id: str = "openai/clip-vit-large-patch14",
    freeze_clip: bool = True,
    device: torch.device = torch.device("cpu"),
) -> SD35ConditioningInverter:
    model = SD35ConditioningInverter(clip_model_id=clip_model_id, freeze_clip=freeze_clip)
    ckpt  = torch.load(path, map_location=device, weights_only=True)
    model.load_state_dict(ckpt["state_dict"])
    return model.to(device)
